language: node_js
node_js:
  - "0.12"
before_install:
  - "curl -L http://git.io/ejPSng | /bin/sh"
sudo: required
env:
  - PACKAGES=./packages/edushareontario:easysearch-core PACKAGE_DIRS=./packages/
  - PACKAGES=./packages/edushareontario:easysearch-components PACKAGE_DIRS=./packages/
  - PACKAGES=./packages/edushareontario:easysearch-elasticsearch PACKAGE_DIRS=./packages/
  - PACKAGES=./packages/edushareontario:easysearch-autosuggest PACKAGE_DIRS=./packages/

